<?php

    use Delos\Dgp\Entities\Permission;
    use Delos\Dgp\Entities\Role;
    use Illuminate\Database\Seeder;

    class PermissionRoleTableSeeder extends Seeder
    {
        public function run()
        {
            $permission_role = [
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Add Email Event')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Add Member Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Add Task Project Type')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Approve Activity')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Cancel Request')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Change Avatar User')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Change Pass Edit User')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('close debit memo')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Create Activity')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Create Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Destroy Activity')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Destroy Alert Debit Memo')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Destroy Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Destroy User')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Emails Event')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('expense menu')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('External Works Report Activity')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Get Pairs By Date Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Get Pairs Descriptions Expense Type')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Get Pairs Requests By Date Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('get Requests By Project Id Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Get Users By Id Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Get Users By Request Id Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('hours Menu')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Activity')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Allocation')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Client')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('index debit memo')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Event')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Home')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Missing Activity')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Notification')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Request')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index Rest')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Index User')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('List Possible Hours Activity')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Manager Menu')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Members Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Members To Add Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Options Debit Memo')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Remove Email Event')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Remove Member Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Remove Task Project Type')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Report Allocation')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Report External Activity')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Report TXT Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('See Proposal Value')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show All Activities')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show All Expenses')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show All Projects')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show All Requests')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show All Rests Unapproved')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show All Users')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show Allocation')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('show debit memo')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show Request')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Show Rests User')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Store Alert Debit Memo')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Tasks Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Tasks To Add Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Update Client')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Update Debit Memo')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Update Expense')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Update Expense After Export')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Add Email Event')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Add Member Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Add Task Project Type')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Airports Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Approve Activity')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Approve Menu')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Approve Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('By Group Client')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('By State City')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Cancel Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Cancellation Signature')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Change Avatar User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('change companies user')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Change Pass Edit User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Check Period Hours Allocation ')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('close debit memo')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Confirm Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Copy Last Values Coast User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Activity')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Advance Money')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Allocation')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Car')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Checkout')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Client')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Company')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Expense')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Financial Rating')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Group')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Lodging')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Project Type')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Rest')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Task')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create Ticket')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Create User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Created Hours Per Task Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Activity')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Alert Debit Memo')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Allocation')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Client')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Expense')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Financial Rating')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Group')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Project Type')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Rest')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy Task')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Destroy User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Edited Hours Per Task Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Emails Event')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('expense menu')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Gcalendar Allocation')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Gcalendar Callback Allocation')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Get Pairs By Date Expense')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Get Pairs Descriptions Expense Type')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Get Pairs Requests By Date Expense')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Get Users By Id Expense')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Get Users By Request Id Expense')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('hours Menu')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Activity')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Allocation')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Budgeted Vs Actual')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Checkout')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Client')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Coast User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('index debit memo')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Event')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Expense')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Financial Rating')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Group')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Home')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Missing Activity')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Notification')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Project Type')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Projects Gantt')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Resources Gantt')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Rest')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Select Plan Signature')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Signature')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index Task')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Index User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('index-company')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('List Possible Hours Activity')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Login User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Manager Menu')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Members Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Members Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Members To Add Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Options Debit Memo')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Owners Index Report')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Refuse Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Remove Email Event')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Remove Member Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Remove Task Project Type')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Report Allocation')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Report External Activity')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Report Menu')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Restore Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Restore User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('See Proposal Value')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Settings Menu')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show All Activities')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show All Expenses')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show All Projects')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show All Requests')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show All Users')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show Allocation')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('show debit memo')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show Details Hours Per Task')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Show Rests User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Store Alert Debit Memo')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Store Allocation')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Store Plan Signature')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Store Tasks Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Summary Request')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Tasks Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Tasks Project Type')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Tasks To Add Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Unapproved Rest')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Client')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Coast User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Expense')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Extra Expenses Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Financial Rating')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Group')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Project Type')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Task')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Update Value User')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('update-company')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Users Index Report')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Approve Activity')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Approve Menu')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Change Avatar User')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Change Pass Edit User')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Check Period Hours Allocation ')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Create Activity')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Destroy Activity')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Download Report Activity')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('expense menu')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('hours Menu')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Index Activity')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('index debit memo')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Index Home')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Index Notification')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Index Project')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('List Possible Hours Activity')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Manager Menu')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Members Project')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Report Allocation')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('show debit memo')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Show Project')],
                ['role_id' => $this->getRoleId('Client'), 'permission_id' => $this->getPermissionId('Tasks Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Add Member Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Add Task Project Type')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Airports Request')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Approve Activity')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Approve Menu')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('By State City')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Cancel Request')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Change Avatar User')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Change Pass Edit User')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Confirm Request')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Create Activity')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Create Advance Money')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Create Car')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Create Expense')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Create Lodging')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Create Request')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Create Rest')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Create Ticket')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Destroy Activity')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Destroy Expense')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Destroy Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Download Report Activity')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('expense menu')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Get Pairs By Date Expense')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Get Pairs Descriptions Expense Type')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Get Pairs Requests By Date Expense')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Get Users By Id Expense')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Get Users By Request Id Expense')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('hours Menu')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Index Activity')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Index Allocation')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Index Expense')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Index Home')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Index Missing Activity')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Index Notification')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Index Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Index Request')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Index Rest')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('List Possible Hours Activity')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Manager Menu')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Members Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Members Request')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Members To Add Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Remove Member Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Remove Task Project Type')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Report Allocation')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Show Allocation')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Show Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Show Request')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Summary Request')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Tasks Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Tasks To Add Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Update Expense')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Add Member Project')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Add Task Project Type')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Airports Request')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Approve Activity')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Approve Menu')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('By State City')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Cancel Request')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Change Avatar User')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Change Pass Edit User')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Confirm Request')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Create Activity')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Create Advance Money')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Create Car')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Create Expense')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Create Lodging')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Create Request')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Create Rest')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Create Ticket')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Destroy Activity')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Destroy Expense')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Destroy Project')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Download Report Activity')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('expense menu')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Get Pairs By Date Expense')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Get Pairs Descriptions Expense Type')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Get Pairs Requests By Date Expense')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Get Users By Id Expense')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Get Users By Request Id Expense')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('hours Menu')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Index Activity')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Index Expense')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Index Home')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Index Missing Activity')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Index Notification')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Index Project')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Index Request')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Index Rest')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('List Possible Hours Activity')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Manager Menu')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Members Project')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Members Request')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Members To Add Project')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Remove Member Project')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Remove Task Project Type')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Report Allocation')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Show Project')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Show Request')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Summary Request')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Tasks Project')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Tasks To Add Project')],
                ['role_id' => $this->getRoleId('Comercial'), 'permission_id' => $this->getPermissionId('Update Expense')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Add Member Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Add Task Project Type')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Airports Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Approve Activity')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Approve Menu')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Approve Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Approve Rest')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('By State City')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Cancel Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Change Avatar User')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Change Pass Edit User')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Confirm Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Create Activity')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Create Advance Money')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Create Allocation')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Create Car')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Create Expense')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Create Lodging')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Create Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Create Rest')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Create Ticket')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Destroy Activity')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Destroy Allocation')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Destroy Expense')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Destroy Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Destroy Rest')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Destroy User')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('expense menu')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Get Pairs By Date Expense')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Get Pairs Descriptions Expense Type')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Get Pairs Requests By Date Expense')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('get Requests By Project Id Expense')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Get Users By Id Expense')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Get Users By Request Id Expense')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('hours Menu')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Activity')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Allocation')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Client')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Expense')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Group')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Home')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Missing Activity')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Notification')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Projects Gantt')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Resources Gantt')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index Rest')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Index User')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('List Possible Hours Activity')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Manager Menu')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Members Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Members Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Members To Add Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Refuse Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Remove Member Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Remove Task Project Type')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Report Allocation')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Report Menu')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show All Activities')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show All Expenses')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show All Projects')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show All Requests')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show All Rests Unapproved')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show All Users')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show Allocation')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show Details Hours Per Task')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Show Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Store Allocation')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Summary Request')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Tasks Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Tasks To Add Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Unapproved Rest')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Update Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Add Email Event')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Add Member Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Add Modules Plan')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Add Permission Module')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Add Permission Role')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Add Permission User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Add Task Project Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('add-user-permission')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Airports Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Approve Activity')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Approve Bank Slip')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Approve Menu')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Approve Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Approve Rest')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('By Group Client')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('By State City')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Cancel Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Cancellation Signature')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Change Avatar User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('change companies user')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Change Group Companies User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Change Group Of Company')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Change Pass Edit User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Check Period Hours Allocation ')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('close debit memo')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Confirm Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Copy Last Values Coast User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Activity')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Advance Money')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Airport')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Allocation')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Car')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Car Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Checkout')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create City')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Client')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Company')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Financial Rating')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Group')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Group Company')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Holiday')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Lodging')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Module')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Permission')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Place')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Plan')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Project Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Rest')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Role')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create State')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Task')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Ticket')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create Transportation Facility')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Create User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Created Hours Per Task Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Activity')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Airport')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Alert Debit Memo')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Allocation')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Bank Slip')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Car Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy City')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Client')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Financial Rating')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Group')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Holiday')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Module')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Permission')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Place')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Plan')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Project Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Rest')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Role')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy State')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Task')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy Transportation Facility')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Destroy User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Download Report Activity')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Edited Hours Per Task Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Emails Event')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('expense menu')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('External Works Report Activity')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Gcalendar Allocation')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Gcalendar Callback Allocation')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Get Pairs By Date Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Get Pairs Descriptions Expense Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Get Pairs Requests By Date Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('get Requests By Project Id Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Get Users By Id Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Get Users By Request Id Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('hours Menu')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Activity')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Airport')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Allocation')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Audit')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Bank Slip')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Budgeted Vs Actual')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Car Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Checkout')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index City')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Client')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Coast User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('index debit memo')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Event')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Financial Rating')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Group')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Group Company')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Holiday')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Home')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Missing Activity')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Module')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Notification')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Permission')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Place')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Plan')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Project Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Projects Gantt')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Resources Gantt')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Rest')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Role')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Select Plan Signature')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Signature')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index State')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Task')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index Transportation Facility')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Index User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('index-company')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('List Possible Hours Activity')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('List User Permissions')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Login User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Manage Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Manager Menu')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Members Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Members Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Members To Add Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Modules Plan')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Options Debit Memo')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Owners Index Report')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Permissions Module')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Permissions Role')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Permissions User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Refuse Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Remove Email Event')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Remove Member Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Remove Module Plan')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Remove Permission Module')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Remove Permission Role')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Remove Permission User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Remove Task Project Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('remove-user-permission')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Report Allocation')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Report External Activity')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Report Menu')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Report TXT Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Restore Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Restore User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('See Proposal Value')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Settings Menu')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show All Activities')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show All Expenses')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show All Projects')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show All Requests')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show All Rests Unapproved')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show All Users')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show Allocation')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show Audit')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('show debit memo')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show Details Hours Per Task')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Show Rests User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Store Alert Debit Memo')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Store Allocation')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Store Plan Signature')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Store Tasks Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Summary Request')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Tasks Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Tasks Project Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Tasks To Add Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Unapproved Rest')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Airport')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Bank Slip')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Car Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update City')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Client')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Coast User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Debit Memo')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Expense')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Expense After Export')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Extra Expenses Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Financial Rating')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Group')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Group Company')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Holiday')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Module')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Permission')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Place')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Plan')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Project Type')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Role')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update State')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Task')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Transportation Facility')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Update Value User')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('update-company')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Users Index Report')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Proposal Values Create Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Proposal Values Destroy Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Proposal Values Index Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Proposal Values Store Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Proposal Values Edit Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Proposal Values Update Project')],
                ['role_id' => $this->getRoleId('Administrative'), 'permission_id' => $this->getPermissionId('Proposal Values Description Report Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Proposal Values Create Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Proposal Values Destroy Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Proposal Values Index Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Proposal Values Store Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Proposal Values Edit Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Proposal Values Description Report Project')],
                ['role_id' => $this->getRoleId('Administrator'), 'permission_id' => $this->getPermissionId('Proposal Values Update Project')],
                ['role_id' => $this->getRoleId('Collaborator'), 'permission_id' => $this->getPermissionId('Proposal Values Index Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Proposal Values Create Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Proposal Values Destroy Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Proposal Values Index Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Proposal Values Store Project')],
                ['role_id' => $this->getRoleId('Manager'), 'permission_id' => $this->getPermissionId('Proposal Values Description Report Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Proposal Values Create Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Proposal Values Destroy Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Proposal Values Index Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Proposal Values Store Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Proposal Values Edit Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Proposal Values Update Project')],
                ['role_id' => $this->getRoleId('Root'), 'permission_id' => $this->getPermissionId('Proposal Values Description Report Project')],

            ];

            foreach ( $permission_role as $index => $item ) {
                \DB::transaction(function () use ($item) {
                    \DB::table('permission_role')
                       ->insert($item);
                });
            }
        }

        private function getRoleId(string $name): int
        {
            return Role::where('name', $name)
                         ->first()->id;
        }

        private function getPermissionId(string $name): int
        {
            return Permission::where('name', $name)
                             ->first()->id;
        }
    }